language: node_js
node_js:
  - "11"
before_install:
  - npm install -g firebase-tools
install:
  - npm install
cache: npm
script:
 - npm run build
after_install:
 - cd public
after_success: "firebase deploy --token $FIREBASE_TOKEN --project getryzerweb"
